%%
clear;clc

%! Prepare GRAM and ORIGINAL folders first !%
root_dir = 'E:\Datasets\SVHN\all';
feat_name = 'raw';
mix_num = 500;

vars = all_vars(root_dir, feat_name, mix_num);
write_config(vars);

hmm_dir  = vars.flat_hmm_dir;      % start with flat hmms

hmm_defs_path = fullfile(hmm_dir, vars.hmm_defs);
floor_path = fullfile(hmm_dir, vars.hmm_vfloors);

if ~exist(hmm_dir, 'dir'), mkdir(hmm_dir); end

% embedded training
cmd_emb = strjoin({'HERest.exe' ...
               '-C' vars.htk_cfg_file...
               '-H' hmm_defs_path ...
               '-H' floor_path ...
               '-S' vars.tr.samp_list ...
               '-I' vars.tr.phone_mlf...
               '-M' hmm_dir ...
               vars.phone_list})

% decoding
cmd_decode = strjoin({'HVite.exe' vars.global_opt ...
    '-C' vars.htk_cfg_file...
    '-o SWC' ...
    '-H' hmm_defs_path ...
    '-H' floor_path ...
    '-S' vars.te.samp_list ...
    '-i' vars.te.rec_w_mlf ...
    '-w' vars.wdnet_path ...
    vars.dict_path ...
    vars.phone_list});

% evaluation
cmd_eval = strjoin({'HResults.exe' vars.global_opt ...
    '-f' ...
    '-t' ...
    '-I' vars.te.word_mlf ...
    vars.phone_list ...
    vars.te.rec_w_mlf});

cmd_rec = sprintf('%s & %s', cmd_decode, cmd_eval)