% train with a specific N_ALL_MIX

%% htk configuration
clear; clc;

n_all_mix    = 800;
root_dir     = 'D:/dataset/SVHN/crop';
separate_dir = ['mix' num2str(n_all_mix)];

mix_vars;

%% gram, phone_list, phone_mlf
% prepare_gram(vars);
% generate_lists(vars);

%% Build Init model
init_hmm_model(vars);

%% Embedded training with HERest
hmm_dir  = fullfile(vars.hmm_dir, 'flat');      % start with flat hmms
hmm_defs_path = fullfile(hmm_dir, vars.hmm_defs);
floor_path = fullfile(hmm_dir, vars.hmm_vfloors);
if ~exist(hmm_dir, 'dir'), mkdir(hmm_dir); end

% embedded training
cmd_emb = strjoin({'HERest.exe' ...
               '-C' vars.htk_cfg_file...
               '-H' hmm_defs_path ...
               '-H' floor_path ...
               '-S' vars.tr.samp_list ...
               '-I' vars.tr.phone_mlf...
               '-M' hmm_dir ...
               vars.phone_list})

% decoding
cmd_decode = strjoin({'HVite.exe' vars.global_opt ...
    '-C' vars.htk_cfg_file...
    '-o SWC' ...
    '-H' hmm_defs_path ...
    '-H' floor_path ...
    '-S' vars.te.samp_list ...
    '-i' vars.te.rec_w_mlf ...
    '-w' vars.wdnet_path ...
    vars.dict_path ...
    vars.phone_list});

% evaluation
cmd_eval = strjoin({'HResults.exe' vars.global_opt ...
    '-f' ...
    '-t' ...
    '-I' vars.te.word_mlf ...
    vars.phone_list ...
    vars.te.rec_w_mlf});

cmd_rec = sprintf('%s & %s', cmd_decode, cmd_eval)
