function hybrid_decoding(hmm_dir, vars)
hmm_defs_path = fullfile(hmm_dir, vars.hmm_defs);
floor_path    = fullfile(hmm_dir, vars.hmm_vfloors);

ds = vars.te;

% log_path = fullfile(hmm_dir, 'hybrid_vite.log');

cmd = strjoin({'hvite_dnn_test.exe' vars.global_opt ...
               '-C' vars.htk_cfg_file...
               '-o SC' ...
               '-H' hmm_defs_path ...
               '-H' floor_path ...
               '-S' ds.samp_list ...
               '-i' ds.rec_w_mlf ...
               '-w' vars.wdnet_path ...
               vars.dict_path ...
               vars.phone_list});
htk_run(cmd, mfilename('fullpath'));

%%
% fprintf('log: %s\n', log_path);

cmd = strjoin({'hvite_dnn_test.exe' vars.global_opt ...
               '-f' ...
               '-o SWC' ...
               '-H' hmm_defs_path ...
               '-H' floor_path ...
               '-S' ds.samp_list ...
               '-i' ds.rec_s_mlf ...
               '-w' vars.wdnet_path ...
               vars.dict_path ...
               vars.phone_list});
htk_run(cmd, mfilename('fullpath'));

