function decoding(hmm_dir, vars)
hmm_defs_path = fullfile(hmm_dir, vars.hmm_defs);
floor_path    = fullfile(hmm_dir, vars.hmm_vfloors);

ds = vars.te;

% log_path = fullfile(hmm_dir, 'vite.log');

cmd = strjoin({'HVite' vars.global_opt ...
    '-C' vars.htk_cfg_file...
    '-o SWC' ...
    '-H' hmm_defs_path ...
    '-H' floor_path ...
    '-S' ds.samp_list ...
    '-i' ds.rec_w_mlf ...
    '-w' vars.wdnet_path ...
    vars.dict_path ...
    vars.phone_list});
    % ['>' log_path]});
htk_run(cmd, mfilename('fullpath'));

% fprintf('log: %s\n', log_path);