function evaluate(vars)
ds = vars.te;
cmd = strjoin({'HResults.exe' vars.global_opt ...
    '-f' ...
    '-t' ...
    '-I' ds.word_mlf ...
    vars.phone_list ...
    vars.te.rec_w_mlf});

htk_run(cmd, mfilename('fullpath'));