function wins = sliding_window(im_wid, im_hei, win_wid, n_overlap)
% WINS = SLIDING_WINDOW(IM_WID, IM_HEI, WIN_WID, N_OVERLAP) Generate sliding 
% windows. The windows are struct arrays. 
step  = win_wid-n_overlap;
win_x2 = win_wid: step : im_wid;
win_x1 = win_x2-win_wid+1;
wins = struct('x', num2cell(win_x1)',...
              'y', 1,...
              'wid', win_wid,...
              'hei', im_hei,...
              'n_olp', n_overlap);
